import React from 'react';
import type { Metadata } from 'next';
import { ShieldCheck, Sparkles, Crown, Heart, Zap } from 'lucide-react';
import { SEO_REGISTRY } from '@/data/seo-registry';
import { FF_GIRLS_NAMES, FF_GIRLS_CATEGORIES } from '@/data/free-fire-content';
import { Breadcrumbs } from '@/components/seo/Breadcrumbs';
import { CopyCardGrid } from '@/components/seo/CopyCardGrid';
import { GeneratorCtaCard } from '@/components/seo/GeneratorCtaCard';
import { RelatedPagesNav } from '@/components/seo/RelatedPagesNav';
import { FaqAccordion } from '@/components/seo/FaqAccordion';

const pageData = SEO_REGISTRY['free-fire-names-for-girls'];

export const metadata: Metadata = {
  title: pageData.title,
  description: pageData.description,
  alternates: {
    canonical: pageData.canonical,
  },
  openGraph: {
    title: pageData.title,
    description: pageData.description,
    url: pageData.canonical,
    type: 'website',
  },
};

const FAQS = [
  {
    question: 'What symbols work best for Free Fire girl names?',
    answer:
      'Popular symbols for female players include crowns (👑, 亗), delicate wings (꧁ ꧂), floral symbols (✿, ❀), stars (✧, ★), and celestial moons (☾). You can also use elegant cursive font scripts generated by NameStylePro.',
  },
  {
    question: 'How can I make my nickname look cute yet intimidating?',
    answer:
      'A great technique is pairing a fierce keyword with an aesthetic symbol. For example, ✿POISON_IVY✿, ⚡Valkyrie⚡, or 亗DIVA亗 communicate both elegance and lethal in-game skill.',
  },
  {
    question: 'Do cursive letters fit into the 12-character limit?',
    answer:
      'Mathematical script (cursive) letters count as valid Unicode characters in Free Fire. Because decorative scripts use mathematical alphanumeric symbols, keep your base name to around 6 to 9 letters to ensure it remains within the customary 12-character limit.',
  },
  {
    question: 'How do I paste a girl name into Free Fire on iPhone or Android?',
    answer:
      'Tap the Copy button next to any name above to save it to your clipboard. In Free Fire, tap your profile avatar, tap the pencil edit icon next to your nickname, long-press the text input box, choose "Paste", and confirm with Diamonds or a Name Change Card.',
  },
];

export default function FreeFireGirlsPage() {
  return (
    <div className="max-w-5xl mx-auto px-4 py-6 md:py-10 space-y-10">
      {/* Breadcrumbs */}
      <Breadcrumbs
        items={[
          { label: 'Free Fire', href: '/free-fire-names' },
          { label: 'Free Fire Names for Girls' },
        ]}
      />

      {/* Hero Header */}
      <header className="text-center space-y-4 max-w-3xl mx-auto pt-2">
        <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full text-xs font-bold bg-pink-50 text-pink-800 border border-pink-200">
          <Sparkles className="w-3.5 h-3.5 text-pink-600 fill-pink-500" />
          <span>Aesthetic & Fierce Female Nicknames for Free Fire</span>
        </div>

        <h1 className="text-3xl sm:text-4xl md:text-5xl font-black text-slate-900 tracking-tight leading-tight">
          Free Fire Names for Girls
        </h1>

        <p className="text-base sm:text-lg text-slate-600 max-w-2xl mx-auto font-medium leading-relaxed">
          Browse stylish, cute, and fierce Free Fire names designed for girls. From queen crowns and
          celestial fonts to warrior tags, find the perfect nickname ready to copy and paste.
        </p>
      </header>

      {/* Curated Copy Grid */}
      <section className="space-y-4">
        <div className="flex items-center justify-between">
          <h2 className="text-xl font-bold text-slate-900">Girl Gamer Tags & Aesthetic Names</h2>
          <span className="text-xs text-slate-500">1-Tap Copy to Clipboard</span>
        </div>

        <CopyCardGrid
          items={FF_GIRLS_NAMES}
          categories={FF_GIRLS_CATEGORIES}
          charLimitWarning={12}
          placeholder="Search girl names (queen, angel, diva)..."
        />
      </section>

      {/* Generator CTA */}
      <GeneratorCtaCard
        title="Create a Custom Aesthetic Girl Name"
        description="Type your favorite nickname into our generator to transform it into elegant cursive fonts, floral brackets, and royal crown designs."
        buttonText="Generate Girl Names"
      />

      {/* Practical Guide */}
      <section className="bg-slate-50 rounded-3xl p-6 sm:p-8 border border-slate-200 space-y-6 text-slate-700 leading-relaxed">
        <div className="space-y-2">
          <h2 className="text-2xl font-black text-slate-900 tracking-tight">
            Design Ideas for Free Fire Girl Nicknames
          </h2>
          <p className="text-sm sm:text-base text-slate-600">
            Female gamers in Free Fire typically choose between three distinct aesthetic directions:
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-1 text-sm">
          <div className="bg-white p-5 rounded-2xl border border-slate-200 space-y-2">
            <div className="w-8 h-8 rounded-xl bg-pink-50 text-pink-600 flex items-center justify-center font-bold">
              <Crown className="w-4 h-4" />
            </div>
            <h3 className="font-bold text-slate-900">Royal & Goddess Styles</h3>
            <p className="text-slate-600 text-xs leading-relaxed">
              Focus on terms of authority like Queen, Empress, Athena, or Duchess. Pair with royal crowns
              (亗, 👑) and symmetrical wings for an elite presence.
            </p>
          </div>

          <div className="bg-white p-5 rounded-2xl border border-slate-200 space-y-2">
            <div className="w-8 h-8 rounded-xl bg-pink-50 text-pink-600 flex items-center justify-center font-bold">
              <Heart className="w-4 h-4" />
            </div>
            <h3 className="font-bold text-slate-900">Soft & Cute Aesthetics</h3>
            <p className="text-slate-600 text-xs leading-relaxed">
              Incorporate subtle floral symbols (✿, ❀), celestial tags (☾, ✧), or soft pastel words like
              Kitty, Daisy, or Sweetie using clean spaced letters.
            </p>
          </div>

          <div className="bg-white p-5 rounded-2xl border border-slate-200 space-y-2">
            <div className="w-8 h-8 rounded-xl bg-pink-50 text-pink-600 flex items-center justify-center font-bold">
              <Zap className="w-4 h-4" />
            </div>
            <h3 className="font-bold text-slate-900">Fierce Warrior Personas</h3>
            <p className="text-slate-600 text-xs leading-relaxed">
              Channel legendary heroines with names like Valkyrie, Huntress, Siren, or Medusa, accented by
              lightning bolts (⚡) and sharp crosshairs.
            </p>
          </div>
        </div>

        <div className="bg-pink-50/80 border border-pink-200/80 rounded-2xl p-4 flex items-start gap-3 text-xs text-pink-900 leading-relaxed">
          <ShieldCheck className="w-5 h-5 text-pink-600 shrink-0 mt-0.5" />
          <div>
            <strong className="font-bold">Game Limit Reminder:</strong> While Free Fire allows decorative
            Unicode glyphs, ensure your nickname does not exceed the customary 12-character limit. Always verify
            the in-game preview before finalizing.
          </div>
        </div>
      </section>

      {/* Internal Links */}
      <RelatedPagesNav currentPageId="free-fire-names-for-girls" />

      {/* FAQ */}
      <FaqAccordion faqs={FAQS} />
    </div>
  );
}
