import React from 'react';
import type { Metadata } from 'next';
import Link from 'next/link';
import { Camera, ShieldCheck, Sparkles, Wand2, Type, Heart } from 'lucide-react';
import { SEO_REGISTRY } from '@/data/seo-registry';
import { INSTAGRAM_NAMES_LIST, INSTAGRAM_NAMES_CATEGORIES } from '@/data/social-content';
import { Breadcrumbs } from '@/components/seo/Breadcrumbs';
import { CopyCardGrid } from '@/components/seo/CopyCardGrid';
import { GeneratorCtaCard } from '@/components/seo/GeneratorCtaCard';
import { RelatedPagesNav } from '@/components/seo/RelatedPagesNav';
import { FaqAccordion } from '@/components/seo/FaqAccordion';

const pageData = SEO_REGISTRY['instagram-names'];

export const metadata: Metadata = {
  title: pageData.title,
  description: pageData.description,
  alternates: {
    canonical: pageData.canonical,
  },
  openGraph: {
    title: pageData.title,
    description: pageData.description,
    url: pageData.canonical,
    type: 'website',
  },
};

const SOCIAL_SUB_LINKS = [
  {
    title: 'Instagram Name Generator',
    href: '/instagram-name-generator',
    desc: 'Generate fancy bio fonts, small capitals, and decorative profile names.',
    icon: Wand2,
    color: 'text-purple-600 bg-purple-50 border-purple-100',
  },
  {
    title: 'Aesthetic Username Generator',
    href: '/aesthetic-username-generator',
    desc: 'Transform words into cursive, spaced, and cute aesthetic typography.',
    icon: Type,
    color: 'text-pink-600 bg-pink-50 border-pink-100',
  },
  {
    title: 'Aesthetic Username Ideas',
    href: '/aesthetic-usernames',
    desc: 'Curated cottagecore, celestial, and soft username collections.',
    icon: Heart,
    color: 'text-rose-600 bg-rose-50 border-rose-100',
  },
];

const FAQS = [
  {
    question: 'What is the difference between an Instagram Username and Display Name?',
    answer:
      'Your Instagram Username (@handle) is your unique account ID used for logins and mentions, restricted to letters, numbers, periods, and underscores. Your Display Name is the bold title shown at the top of your bio, which fully supports fancy Unicode fonts, cursive script, and special symbols.',
  },
  {
    question: 'How do I add stylish fonts to my Instagram bio?',
    answer:
      'Browse our curated styles above or type your text into our generator and click "Copy". Open Instagram, tap "Edit Profile", paste the text into the Name or Bio field, and tap the checkmark to save.',
  },
  {
    question: 'Will these fonts appear correctly to my followers on both iPhone and Android?',
    answer:
      'Yes. All styles generated by NameStylePro utilize standard Unicode alphanumeric characters natively supported by iOS, Android, Windows, and macOS, ensuring your bio looks consistent on every device.',
  },
];

export default function InstagramNamesHubPage() {
  return (
    <div className="max-w-5xl mx-auto px-4 py-6 md:py-10 space-y-10">
      {/* Breadcrumbs */}
      <Breadcrumbs items={[{ label: 'Social', href: '/instagram-names' }, { label: 'Stylish Instagram Names' }]} />

      {/* Hero Header */}
      <header className="text-center space-y-4 max-w-3xl mx-auto pt-2">
        <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full text-xs font-bold bg-pink-50 text-pink-800 border border-pink-200">
          <Camera className="w-3.5 h-3.5 text-pink-600" />
          <span>Aesthetic Instagram Fonts & Bio Directory</span>
        </div>

        <h1 className="text-3xl sm:text-4xl md:text-5xl font-black text-slate-900 tracking-tight leading-tight">
          Stylish Instagram Names
        </h1>

        <p className="text-base sm:text-lg text-slate-600 max-w-2xl mx-auto font-medium leading-relaxed">
          Discover hundreds of stylish Instagram names, aesthetic bio handles, and fancy profile fonts.
          Copy elegant cursive, clean small capitals, and cute symbols ready to paste into Instagram.
        </p>
      </header>

      {/* Sub-Category Links */}
      <section className="space-y-4">
        <div className="flex items-center justify-between">
          <h2 className="text-xl font-bold text-slate-900">Explore Social Font Tools</h2>
          <span className="text-xs text-slate-500 font-medium">Specialized generators</span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3.5">
          {SOCIAL_SUB_LINKS.map((sub) => {
            const Icon = sub.icon;
            return (
              <Link
                key={sub.href}
                href={sub.href}
                className="group p-4 bg-white rounded-2xl border border-slate-200 hover:border-brand-300 hover:shadow-md transition-all flex items-start gap-3.5"
              >
                <div className={`p-2.5 rounded-xl border shrink-0 ${sub.color}`}>
                  <Icon className="w-5 h-5" />
                </div>
                <div className="space-y-1">
                  <h3 className="font-bold text-slate-900 text-sm group-hover:text-brand-600 transition-colors">
                    {sub.title}
                  </h3>
                  <p className="text-xs text-slate-500 leading-relaxed">{sub.desc}</p>
                </div>
              </Link>
            );
          })}
        </div>
      </section>

      {/* Curated Copy Grid */}
      <section className="space-y-4">
        <div className="flex items-center justify-between">
          <h2 className="text-xl font-bold text-slate-900">Curated Instagram Bio Names</h2>
          <span className="text-xs text-slate-500">1-Tap Copy</span>
        </div>

        <CopyCardGrid
          items={INSTAGRAM_NAMES_LIST}
          categories={INSTAGRAM_NAMES_CATEGORIES}
          placeholder="Search Instagram styles (cursive, velvet, soul)..."
        />
      </section>

      {/* Generator CTA */}
      <GeneratorCtaCard
        title="Create Your Own Custom Instagram Font Style"
        description="Type your real name or bio text into NameStylePro to generate 1,000+ fancy fonts, cursive scripts, and cute symbols with instant 1-tap copy."
        buttonText="Try Instagram Font Generator"
      />

      {/* Practical Guide */}
      <section className="bg-slate-50 rounded-3xl p-6 sm:p-8 border border-slate-200 space-y-6 text-slate-700 leading-relaxed">
        <div className="space-y-2">
          <h2 className="text-2xl font-black text-slate-900 tracking-tight">
            How to Style Your Instagram Bio (Rules & Steps)
          </h2>
          <p className="text-sm sm:text-base text-slate-600">
            Make the most of Instagram\'s formatting capabilities:
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-1 text-sm">
          <div className="bg-white p-5 rounded-2xl border border-slate-200 space-y-2">
            <h3 className="font-bold text-slate-900">1. Style Your Display Name</h3>
            <p className="text-slate-600 text-xs leading-relaxed">
              Instagram limits you to changing your Display Name twice within 14 days. Preview your favorite style on NameStylePro first so you are satisfied with the result.
            </p>
          </div>

          <div className="bg-white p-5 rounded-2xl border border-slate-200 space-y-2">
            <h3 className="font-bold text-slate-900">2. Keep Bio Bio-Line Short</h3>
            <p className="text-slate-600 text-xs leading-relaxed">
              Bios have a 150-character limit. Using clean small capitals or concise cursive phrases keeps your bio easy to read on mobile screens without truncation.
            </p>
          </div>

          <div className="bg-white p-5 rounded-2xl border border-slate-200 space-y-2">
            <h3 className="font-bold text-slate-900">3. Use High-Contrast Symbols</h3>
            <p className="text-slate-600 text-xs leading-relaxed">
              Subtle symbols like ✿, ☾, or ⚡ break up lines of text and act as natural bullet points for your hobbies, location, and links.
            </p>
          </div>
        </div>

        <div className="bg-pink-50/80 border border-pink-200/80 rounded-2xl p-4 flex items-start gap-3 text-xs text-pink-900 leading-relaxed">
          <ShieldCheck className="w-5 h-5 text-pink-600 shrink-0 mt-0.5" />
          <div>
            <strong className="font-bold">Accessibility Reminder:</strong> While fancy fonts look stunning for
            names and headers, keep critical contact details (like email addresses or links) in standard text for
            screen-reader accessibility.
          </div>
        </div>
      </section>

      {/* Internal Links */}
      <RelatedPagesNav currentPageId="instagram-names" />

      {/* FAQ */}
      <FaqAccordion faqs={FAQS} />
    </div>
  );
}
